# Generated by Django 6.0.1 on 2026-03-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Traiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcomplet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('adresse', models.CharField(max_length=200)),
                ('est_actif', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('datedecreation', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.CharField(max_length=9)),
                ('image', models.URLField(blank=True, null=True)),
                ('specialites', models.ManyToManyField(to='services.specialite')),
            ],
        ),
    ]
