# Generated by Django 6.0.3 on 2026-04-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traiteur',
            name='est_actif',
            field=models.BooleanField(default=False),
        ),
    ]
