# Generated by Django 6.0.3 on 2026-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_traiteur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traiteur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='traiteurs/'),
        ),
    ]
